### ISSUE TITLE
No targets found

### ISSUE THREAD

**Issue by carciente** [idleberg/atom-build-dart-sass#1]
Hello,

Thank you for the package, I am a noob and this is probably user error, but when I press F7 I get no targets found. I have a .sass file open and this is happening after closing Atm and open it again. Before that, I was able to successfully compile (transpile) the test file to a .css.

Any idea of what I can bedoing wrong?

Thanks

**Comment by idleberg** [comment]
It sounds like opened a single file. For whatever reason, the `build` plugin (which this package requires) only works with projects, not single files. To create a project, open the folder containing your `.sass` file in Atom.

**Comment by carciente** [comment]
Thank you for your fast answer. Unfortunately that is not the case. I have opened the project folder and when I try to compile I get this message:

_No configuration to build this project exists.
Hide Stack Trace
No eligible build target.: No configuration to build this project exists.
    at /home/chuao/.atom/packages/build/lib/build.js:113:15_

And when I press F7 I get:

_No targets found._

As I said before it was working on this same project when I just installed, but it doesn't work after I restarted Atom.

Any idea? Is there any information I can provide to help understand the problem?

**Comment by idleberg** [comment]
Looking at a code, I have an assumption. If I'm not mistaken, the CLI for Dart Sass was initially called `dart-sass`, so it could be distinguished from the Ruby and Node implementations. Can you confirm that the CLI now is simply called `sass`?

**Comment by carciente** [comment]
The executable's name is sass and I installed it following these instructions:

### Standalone

You can download the standalone Dart Sass archive for your operating
system—containing the Dart VM and the snapshot of the executable—from [the
GitHub release page][]. Extract it, [add the directory to your path][], restart
your terminal, and the `sass` executable is ready to run!

[the GitHub release page]: https://github.com/sass/dart-sass/releases/
[add the directory to your path]: https://katiek2.github.io/path-doc/

![image](https://user-images.githubusercontent.com/42921138/88558302-90fbba00-cfe8-11ea-9fff-166b3e1e6f6f.png)

**Comment by carciente** [comment]
I created a symbolic link called dart-sass pointing to sass and it's working now! I suggest adding that step to the instructions.
